services:
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_FIREBASE_API_KEY=AIzaSyB2nyRt7Z2TkBfmA7fyb14-vTdXMu1Wkvk
      - REACT_APP_FIREBASE_AUTH_DOMAIN=z-prefix-dev.firebaseapp.com
      - REACT_APP_FIREBASE_PROJECT_ID=z-prefix-dev
      - REACT_APP_FIREBASE_STORAGE_BUCKET=z-prefix-dev.appspot.com
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=497969693647
      - REACT_APP_FIREBASE_APP_ID=1:497969693647:web:4dedb485d68fe2834b48ba
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    networks:
      - zpre-net
    depends_on:
      - server

  server:
    build: ./server
    container_name: server
    environment:
      - DB_CONNECTION_STRING=postgres://postgres:password@database/zpre-posting
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
    networks:
      - zpre-net
    depends_on:
      - database

  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zpre-posting
    ports:
      - 5432:5432
    volumes:
      - miniapp_zpre:/var/lib/postgresql/data/
    networks:
      - zpre-net

volumes:
  miniapp_zpre:
    external: true

networks:
  zpre-net:
    driver: bridge


# docker volume create miniapp_zpre